### ISSUE TITLE
grunt dist-mac: Unable to build a max osx64 distribution sample apps (multiple errors)

### ISSUE THREAD

**Issue by reduxdj** [Dica-Developer/generator-node-webkit#59] opened 2015-01-02 15:41 UTC
The first error is that when trying to install a frameless window, the jshint fails on jquery.

    591 |                xml.async = "false";
                                            ^ Strings must use singlequote.
    597 |        if ( !xml || !xml.documentElement || xml.getElementsByTagName( "parsererror" ).length ) {
                                                                                             ^ Strings must use singlequote.
>> Too many errors. (6% scanned).

(Commenting out jshint fixes the first problem)

Then when trying to do a chmod on the file, there's a file missing:

Running "chmod64" task
Warning: ENOENT, no such file or directory 'dist/MacOS64/testapp.app/Contents/Frameworks/node-webkit Helper EH.app/Contents/MacOS/node-webkit Helper EH' Use --force to continue.

**Comment by mschaaf** [comment] 2015-01-04 11:56
The first error comes from the sample app not following our jshint settings this can be easily ignored with the option --force added to the command line of grunt dist-mac. You don't need to disable it in the grunt js file. At the end you should run ```grunt dist-mac --force```

To be able to help you on the second problem I need to know
1. What sample app you tried?
2. What node-webkit version you are building for?
3. What are the exact steps to reproduce?
4. On what OS you are trying to build the OSX64 dist?

**Comment by coderush** [comment] 2015-01-04 20:51
same problem for me. Answering your questions : 
1. What sample app you tried? file explorer
2. What node-webkit version you are building for?  v0.10.5
3. What are the exact steps to reproduce? step 1) yo node-webkit ; step 2) grunt dist-mac
4. On what OS you are trying to build the OSX64 dist? OSX 10.9.4

**Comment by mschaaf** [comment] 2015-01-04 21:45
Thanks for your answer I will try to reproduce.

**Comment by mschaaf** [comment] 2015-01-19 07:28
I can reproduce this.

Could you please check the following:

1. have the folder and all sub folders and files the permission for the user you run yo node-webkit with to read and write?
2. Did you download the mac 64 or 32 bit version of node-webkit?
3. Please paste the complete output of your build starting from entering yo node-webkit.

**Comment by mschaaf** [comment] 2015-01-19 08:18
I get this error if I download node-webkit for macosx 32 bit and then use the grunt dist-mac task which is for the osx64 version. You have to use the grunt dist-mac32 task to build this version. Could also please check if this fixes your problem?

**Comment by mschaaf** [comment] 2015-01-19 08:24
I clarified this in the wiki to.

**Comment by mschaaf** [comment] 2015-02-02 08:19
Thank you for your help to improve generator-node-webkit. We will close this issue because it seems to be solved and there is no further activity since 14 days. Feel free to reopen if the issue still persists and give further information.

**Closed by mschaaf** 2015-02-02 08:19 UTC
Labels: pending

**Comment by KameshAnandan** [comment] 2015-02-03 21:59
I am facing the same issue for both mac32 and mac64
1. What sample app you tried? just blank project - no sample 
2. What node-webkit version you are building for? v0.11.6 - 64 bit version
3. What are the exact steps to reproduce? step 1) yo node-webkit ; step 2) grunt dist-mac (or) grunt dist-mac32
4. On what OS you are trying to build the OSX64 dist? OSX 10.8.5
